@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "p:AbstractFindClientCommandParser" as AbstractFindClientCommandParser LOGIC_COLOR
participant "p:AbstractFindClientCommand" as AbstractFindClientCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute()
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(keywords)
activate AddressBookParser

create AbstractFindClientCommandParser
AddressBookParser -> AbstractFindClientCommandParser
activate AbstractFindClientCommandParser

create AbstractFindClientCommand
AbstractFindClientCommandParser -> AbstractFindClientCommand : parse(keywords)
activate AbstractFindClientCommand
AbstractFindClientCommandParser <-- AbstractFindClientCommand
deactivate AbstractFindClientCommand

AbstractFindClientCommandParser --> AddressBookParser : p
deactivate AbstractFindClientCommandParser

AddressBookParser --> LogicManager : p
deactivate AddressBookParser

LogicManager -> AbstractFindClientCommand : execute()
activate AbstractFindClientCommand

    AbstractFindClientCommand -> Model : updateFilteredClientList(predicate)
    activate Model
    Model --> AbstractFindClientCommand
    deactivate Model

create CommandResult
AbstractFindClientCommand -> CommandResult
activate CommandResult
CommandResult --> AbstractFindClientCommand
deactivate CommandResult

AbstractFindClientCommand --> LogicManager : result
deactivate AbstractFindClientCommand
AbstractFindClientCommand -[hidden]-> LogicManager : result

[<--LogicManager
deactivate LogicManager
@enduml
