@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "p:PriorityCommandParser" as PriorityCommandParser LOGIC_COLOR
participant "p:PriorityCommand" as PriorityCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute()
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(indexes)
activate AddressBookParser

create PriorityCommandParser
AddressBookParser -> PriorityCommandParser
activate PriorityCommandParser

create PriorityCommand
PriorityCommandParser -> PriorityCommand : parse(indexes)
activate PriorityCommand
PriorityCommandParser <-- PriorityCommand
deactivate PriorityCommand

PriorityCommandParser --> AddressBookParser : p
deactivate PriorityCommandParser

AddressBookParser --> LogicManager : p
deactivate AddressBookParser

LogicManager -> PriorityCommand : execute()
activate PriorityCommand

loop while indexes is not empty
    PriorityCommand -> Model : getFilteredClientList()
    activate Model
    Model --> PriorityCommand
    deactivate Model

    PriorityCommand -> Model : setClient()
    activate Model
    Model --> PriorityCommand
    deactivate Model
end

create CommandResult
PriorityCommand -> CommandResult
activate CommandResult
CommandResult --> PriorityCommand
deactivate CommandResult

PriorityCommand --> LogicManager : result
deactivate PriorityCommand
PriorityCommand -[hidden]-> LogicManager : result

[<--LogicManager
deactivate LogicManager
@enduml
