@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant "p:PriorityCommand" as PriorityCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "oldClient:Client" as oClient MODEL_COLOR
participant "newClient:Client" as nClient MODEL_COLOR
end box

[-> PriorityCommand : execute(index)
activate PriorityCommand
loop while indexes is not empty
PriorityCommand -> Model : getFilteredClientList()
activate Model

Model --> PriorityCommand
deactivate Model

PriorityCommand -> PriorityCommand : getClientFromIndex(index)
activate PriorityCommand
    PriorityCommand -> oClient
    activate oClient
    oClient --> PriorityCommand
    deactivate oClient
PriorityCommand --> PriorityCommand
deactivate PriorityCommand

PriorityCommand -> PriorityCommand : togglePriority
activate PriorityCommand
    create nClient
    PriorityCommand -> nClient : Client()
    activate nClient
    nClient --> PriorityCommand
    deactivate nClient
PriorityCommand --> PriorityCommand
deactivate PriorityCommand


PriorityCommand -> Model : setClient(oldClient, newClient)
activate Model

Model --> PriorityCommand
deactivate Model

PriorityCommand -> Model : updateFilteredClientList
activate Model

Model --> PriorityCommand
deactivate Model
end
[<--PriorityCommand
deactivate PriorityCommand
@enduml
